version: '3'
services:
  db:
    image: postgres
    volumes:
    - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass yourpassword
    volumes:
    - 'redis:/data'
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
    - .:/myapp
    ports:
    - "3000:3000"
    depends_on:
    - db
    - redis
  cable:
    depends_on:
    - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
    - '28080:28080'
    volumes:
    - '.:/app'
volumes:
  redis:
  postgres:


